remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Leveraging Temporal Contexts to Enhance Vehicle-Infrastructure Cooperative Perception
description: 
show_downloads: false
